
[profile.dev.package.rapier3d]
opt-level = 3

[workspace]
resolver = "2"

members = [
    "runtimes/*",
    "engine",
    "engine_ffmpeg",
    "shock2vr",
    "dark",
    "tools/shodan",
    "tools/dark_viewer",
]
